#! /bin/bash
[ $# -ne 3 ] && echo "params error: [1]->db user; [2]->db password; [3]->merchant" && exit 1

USER=$1
PASSWORD=$2
SUFFIX=$3

TABLE_GOOD=w_inventory_good_${SUFFIX}
TABLE_GOOD_EXTRA=w_inventory_good_extra_${SUFFIX}
TABLE_STOCK_NEW=w_inventory_new_${SUFFIX}
TABLE_STOCK_NEW_DETAIL=w_inventory_new_detail_${SUFFIX}
TABLE_STOCK_NEW_DETAIL_AMOUNT=w_inventory_new_detail_amount_${SUFFIX}

TABLE_STOCK=w_inventory_${SUFFIX}
TABLE_STOCK_NOTE=w_inventory_amount_${SUFFIX}

TABLE_SALE=w_sale_${SUFFIX}
TABLE_SALE_DETAIL=w_sale_detail_${SUFFIX}
TABLE_SALE_DETAIL_AMOUNT=w_sale_detail_amount_${SUFFIX}

TABLE_STOCK_TRANSFER=w_inventory_transfer_${SUFFIX}
TABLE_STOCK_TRANSFER_DETAIL=w_inventory_transfer_detail_${SUFFIX}
TABLE_STOCK_TRANSFER_DETAIL_AMOUNT=w_inventory_transfer_detail_amount_${SUFFIX}

TABLE_STOCK_FIX=w_inventory_fix_${SUFFIX}
TABLE_STOCK_FIX_DETAIL_AMOUNT=w_inventory_fix_detail_amount_${SUFFIX}


mysql -u${USER} -p${PASSWORD} sdiablo <<EOF
DROP TABLE ${TABLE_GOOD};
DROP TABLE ${TABLE_GOOD_EXTRA};

DROP TABLE ${TABLE_STOCK_NEW};
DROP TABLE ${TABLE_STOCK_NEW_DETAIL};
DROP TABLE ${TABLE_STOCK_NEW_DETAIL_AMOUNT};

DROP TABLE ${TABLE_STOCK};
DROP TABLE ${TABLE_STOCK_NOTE};

DROP TABLE ${TABLE_SALE};
DROP TABLE ${TABLE_SALE_DETAIL};
DROP TABLE ${TABLE_SALE_DETAIL_AMOUNT};

DROP TABLE ${TABLE_STOCK_TRANSFER};
DROP TABLE ${TABLE_STOCK_TRANSFER_DETAIL};
DROP TABLE ${TABLE_STOCK_TRANSFER_DETAIL_AMOUNT};

DROP TABLE ${TABLE_STOCK_FIX};
DROP TABLE ${TABLE_STOCK_FIX_DETAIL_AMOUNT};

EOF
