#!/bin/sh

. `dirname $0`/knife-env

##--- Set environment vars knife_<var_name> to defaults if not set

[ "x" = "x$RABBITMQ_ENABLED_PLUGINS_FILE" ] && KNIFE_ENABLED_PLUGINS_FILE=${ENABLED_PLUGINS_FILE}
[ "x" = "x$RABBITMQ_PLUGINS_DIR" ] && KNIFE_PLUGINS_DIR=${PLUGINS_DIR}

##--- End of overridden <var_name> variables

exec erl \
    -pa "${KNIFE_HOME}/ebin" \
    -noinput \
    -hidden \
    -sname knife-plugins$$ \
    -s knife_plugins_main \
    -enabled_plugins_file "$KNIFE_ENABLED_PLUGINS_FILE" \
    -plugins_dist_dir "$KNIFE_PLUGINS_DIR" \
    -extra "$@"
